"""
[GENERATED BY CURSOR]
This script provides functionality to interact with the Notion API.
It allows creating entries in a Notion database and adding content to pages.
"""

import os
from typing import Dict, Any, Optional
from dotenv import load_dotenv
from notion_client import Client
from loguru import logger

def load_api_key() -> str:
    """Load Notion API key from environment variables."""
    load_dotenv()
    api_key = os.getenv("NOTION_API_KEY")
    if not api_key:
        raise ValueError("NOTION_API_KEY not found in environment variables")
    return api_key

def create_database_entry(
    database_id: str,
    properties: Dict[str, Any],
    content: Optional[str] = None
) -> Dict[str, Any]:
    """
    Create a new entry in a Notion database and optionally add content to the page.
    
    Args:
        database_id: The ID of the Notion database
        properties: Dictionary of properties to set for the database entry
        content: Optional content to add to the page
    
    Returns:
        Dict containing the created page information
    """
    notion = Client(auth=load_api_key())
    
    # Create the database entry
    page = notion.pages.create(
        parent={"database_id": database_id},
        properties=properties
    )
    
    # If content is provided, add it to the page
    if content:
        notion.blocks.children.append(
            block_id=page["id"],
            children=[
                {
                    "object": "block",
                    "type": "paragraph",
                    "paragraph": {
                        "rich_text": [
                            {
                                "type": "text",
                                "text": {"content": content}
                            }
                        ]
                    }
                }
            ]
        )
    
    return page

def main():
    """Example usage of the Notion API functions."""
    # Load database ID from environment variables
    load_dotenv()
    database_id = os.getenv('NOTION_DATABASE_ID')

    properties = {
        "Name": {
            "title": [
                {
                    "text": {
                        "content": "Test Entry"
                    }
                }
            ]
        },
        "Status": {
            "status": {
                "name": "In progress"
            }
        },
        "Date": {
            "date": {
                "start": "2025-04-08"
            }
        }
    }
    
    content = "This is a test entry created via the Notion API."
    
    try:
        page = create_database_entry(database_id, properties, content)
        logger.info(f"Successfully created page: {page['url']}")
    except Exception as e:
        logger.error(f"Failed to create Notion entry: {e}")

if __name__ == "__main__":
    main() 
