"""
[GENERATED BY CURSOR]
Module for website scraping functions.
Provides a unified interface for different scraping implementations.
"""

from .basic import scrape as basic_scrape
from .playwright import scrape as playwright_scrape

def scrape(url: str, scraper_type="basic"):
    """
    Scrapes a website and converts to markdown using the specified scraper.
    
    Args:
        url: URL to scrape
        scraper_type: Type of scraper to use ("basic" or "playwright")
    
    Returns:
        tuple: (html_content, markdown_content, title)
    """
    if scraper_type == "basic":
        return basic_scrape(url)
    elif scraper_type == "playwright":
        return playwright_scrape(url)
    else:
        raise ValueError(f"Invalid scraper_type: {scraper_type}")