"""
[GENERATED BY CURSOR]
Base class for website content scrapers.

This module defines the abstract base class `BaseScraper` that all specific
website scrapers should inherit from. It enforces a common interface for
fetching HTML content from a URL.
"""
from abc import ABC, abstractmethod
from typing import Optional

class BaseScraper(ABC):
    """
    Abstract Base Class for website scrapers.

    Concrete implementations must provide a method to scrape a URL and
    return its HTML content.
    """

    @abstractmethod
    def scrape(self, url: str) -> Optional[str]:
        """
        Scrapes the content of the given URL.

        Args:
            url (str): The URL of the webpage to scrape.

        Returns:
            Optional[str]: The HTML content of the webpage as a string if successful,
                           None otherwise.
        """
        pass 