"""
[GENERATED BY CURSOR]
Common utilities for website scrapers.
Contains shared functionality used by both basic and playwright scrapers.
"""

from utils.logging_config import logger
from markdownify import markdownify
from bs4 import BeautifulSoup


def parse_html_to_markdown(html_content):
    """
    Parses HTML content directly to Markdown using markdownify.
    
    Args:
        html_content: The HTML content to parse
        
    Returns:
        tuple: (markdown_content, title) or (None, None) if an error occurs
    """
    try:
        # Extract title using BeautifulSoup
        soup = BeautifulSoup(html_content, 'html.parser')
        title = soup.title.string if soup.title else ""
        
        # Convert to markdown directly
        markdown_content = markdownify(html_content)
        
        return markdown_content, title
    except Exception as e:
        logger.error(f"Error parsing HTML to Markdown: {e}")
        return None, None 