"""
[GENERATED BY CURSOR]
This script loads the processed data from preprocess.py,
and publishes the summarized content to a Notion database.
"""

import os
from dotenv import load_dotenv
# Import the logger from the centralized logging_config module
from utils.logging_config import logger
from connectors.notion import create_database_entry
import json
from datetime import datetime
import pathlib

def load_environment():
    """
    Load and validate all required environment variables for publishing.

    Returns:
        dict: Dictionary containing all required environment variables.

    Raises:
        ValueError: If any required environment variable is missing.
    """
    load_dotenv()

    required_env_vars = {
        'NOTION_DATABASE_ID': os.getenv('NOTION_DATABASE_ID'),
    }

    missing_vars = [var for var, value in required_env_vars.items() if not value]
    if missing_vars:
        raise ValueError(f"Missing required environment variables for publishing: {', '.join(missing_vars)}")

    return required_env_vars

def create_notion_blocks(processed_results, error_content=None):
    """Creates the list of blocks for the Notion page body.
    
    Args:
        processed_results: List of processed content results
        error_content: Optional error log content to include at the end
    """
    children_blocks = []
    for result in processed_results:
        # Add a heading for each channel/podcast
        children_blocks.append({
            "object": "block",
            "type": "heading_3",
            "heading_3": {
                "rich_text": [{"type": "text", "text": {"content": f"{result['channel']} ({result['type']})"}}]
            }
        })

        # Add a toggle block with the title as the toggle text
        title = result.get('title', 'Untitled')
        toggle_block = {
            "object": "block",
            "type": "toggle",
            "toggle": {
                "rich_text": [{"type": "text", "text": {"content": title}}],
                "children": []
            }
        }

        # Add published date to toggle children
        published_at = result.get('published_at', 'Unknown date')
        toggle_block["toggle"]["children"].append({
            "object": "block",
            "type": "bulleted_list_item",
            "bulleted_list_item": {
                "rich_text": [
                    {"type": "text", "text": {"content": f"Published: {published_at}"}}
                ]
            }
        })

        # Add duration to toggle children
        duration = result.get('duration', 'Unknown duration')
        toggle_block["toggle"]["children"].append({
            "object": "block",
            "type": "bulleted_list_item",
            "bulleted_list_item": {
                "rich_text": [
                    {"type": "text", "text": {"content": f"Duration: {duration}"}}
                ]
            }
        })

        # Add stats to toggle children
        stats = result.get('stats', 'Unknown stats')
        toggle_block["toggle"]["children"].append({
            "object": "block",
            "type": "bulleted_list_item",
            "bulleted_list_item": {
                "rich_text": [
                    {"type": "text", "text": {"content": f"Stats: {str(stats)}"}}
                ]
            }
        })       

        # Add summary as a sublist within toggle
        summary = result.get('summary', 'No summary')
        summary_block = {
            "object": "block",
            "type": "bulleted_list_item",
            "bulleted_list_item": {
                "rich_text": [
                    {"type": "text", "text": {"content": "Summary:"}}
                ]
            }
        }

        # If summary is a list, add each item as a sub-bullet
        if isinstance(summary, list):
            summary_children = []
            for item in summary:
                summary_children.append({
                    "object": "block",
                    "type": "bulleted_list_item",
                    "bulleted_list_item": {
                        "rich_text": [
                            {"type": "text", "text": {"content": item}}
                        ],
                        "color": "default"
                    }
                })
            # Add summary children to the summary block
            if summary_children: # Only add children if there are any
                 summary_block["bulleted_list_item"]["children"] = summary_children

        # Add summary block to toggle children
        toggle_block["toggle"]["children"].append(summary_block)

        # Add URL to toggle children
        url = result.get('url', 'No URL')
        if url and url != 'No URL': # Only add bookmark if URL exists
             toggle_block["toggle"]["children"].append({
                 "object": "block",
                 "type": "bookmark",
                 "bookmark": {
                     "url": url,
                     "caption": [],
                 }
             })
        else:
             toggle_block["toggle"]["children"].append({
                 "object": "block",
                 "type": "paragraph",
                 "paragraph": {
                     "rich_text": [{"type": "text", "text": {"content": "URL: Not available"}}]
                 }
             })

        # Add the complete toggle block to children_blocks
        children_blocks.append(toggle_block)

        # Add a divider between items
        children_blocks.append({
            "object": "block",
            "type": "divider",
            "divider": {}
        })

    # Add raw error data in a toggle block at the end
    if error_content:
        logger.info(f"Adding error content to Notion: {error_content[:2000]}")
        # Add heading for errors section
        children_blocks.append({
            "object": "block",
            "type": "heading_3",
            "heading_3": {
                "rich_text": [{"type": "text", "text": {"content": "Program Errors"}}]
            }
        })
        
        # Add error content in a toggle block
        children_blocks.append({
            "object": "block",
            "type": "code",
            "code": {
                "rich_text": [
                    {"type": "text", "text": {"content": error_content[:2000]}} # Limit to 2000 characters
                ],
                "language": "plain text"
            }
        })

    return children_blocks

def main():
    """Main function to load data, process it, and publish to Notion."""
    try:
        # Load environment variables
        env_vars = load_environment()

        # --- Caching Logic for Processed Data ---
        cache_dir = pathlib.Path("data")
        cache_dir.mkdir(exist_ok=True) # Ensure data directory exists
        current_date_str = datetime.now().strftime("%Y-%m-%d")
        cache_file = cache_dir / f"processed_results_{current_date_str}.json"

        if cache_file.exists():
            logger.info(f"Loading filtered results: {cache_file}")
            try:
                with open(cache_file, 'r') as f:
                    processed_results = json.load(f)
            except json.JSONDecodeError:
                logger.error(f"Error decoding cache file {cache_file}. Re-processing.")
                processed_results = None # Force reprocessing if cache is corrupt
            except IOError as e:
                 logger.error(f"Error reading cache file {cache_file}: {e}. Re-processing.")
                 processed_results = None
        else:
            logger.warning("No processed data found for today. Cannot proceed.")
            return

        # check if empty
        if not processed_results:
            logger.warning("No processed results found. Cannot proceed.")
            return
            
        # --- Load error log file if it exists ---
        error_content = None
        error_log_path = cache_dir / f"app_errors_{current_date_str}.log"
        
        if error_log_path.exists() and error_log_path.stat().st_size > 0:
            try:
                with open(error_log_path, 'r') as f:
                    error_content = f.read()
                logger.info(f"Loaded error logs from {error_log_path}")
            except Exception as e:
                logger.error(f"Failed to read error log file {error_log_path}: {str(e)}")
        else:
            logger.info(f"No errors found in log file or file does not exist: {error_log_path}")

        # --- Send to Notion - create a single entry with multiple blocks --- 
        current_date_for_notion = datetime.now().strftime("%Y-%m-%d") # Use consistent date format
        combined_title = f"Daily Update - {current_date_for_notion}"

        # Create Notion properties for the single entry
        properties = {
            "Name": {
                "title": [
                    {
                        "text": {
                            "content": combined_title
                        }
                    }
                ]
            },
            "Status": {
                "status": {
                    "name": "Not started"
                }
            },
            "Date": {
                "date": {
                    "start": current_date_for_notion
                }
            }
        }

        # --- Create Notion block list --- 
        children_blocks = create_notion_blocks(processed_results, error_content)

        # Create single Notion entry with all blocks
        notion_db_id = env_vars['NOTION_DATABASE_ID']
        page = create_database_entry(notion_db_id, properties, children_blocks)

        if page and 'url' in page:
             logger.info(f"Successfully created combined Notion entry: {page['url']}")
        else:
             logger.error(f"Failed to create Notion entry. Response: {page}")

    except Exception as e:
        logger.exception(f"An unexpected error occurred during publishing: {str(e)}")
        # raise # Re-raise if needed for external monitoring

if __name__ == "__main__":
    main() 