"""
[GENERATED BY CURSOR]
Centralized logging configuration for all modules.
This module configures loguru to write logs to the console and error logs to a file.
Supports UTF-8 encoding for proper display of multilingual content including Chinese characters.
"""

import sys
import os
import locale
from loguru import logger
from datetime import datetime
import pathlib

# Set environment variables to ensure proper encoding for stdout
os.environ["PYTHONIOENCODING"] = "utf-8"  # Force Python to use UTF-8 for stdin/stdout/stderr
locale.setlocale(locale.LC_ALL, "")  # Use system's preferred locale

def setup_logging():
    """
    Configure loguru logger to write error logs to a file in the data directory.
    This function is intended to be called once during application initialization.
    Ensures proper encoding for multilingual text including Chinese characters.
    """
    # Ensure data directory exists
    data_dir = pathlib.Path("data")
    data_dir.mkdir(exist_ok=True)
    
    # Generate log filename with current date
    log_file = data_dir / f"app_errors_{datetime.now().strftime('%Y-%m-%d')}.log"
    
    # Remove default handler and add custom handlers
    logger.remove()
    
    # Add stdout handler for all levels with UTF-8 encoding
    logger.add(sys.stdout, level="INFO")
    
    # Add file handler for WARNING and above with UTF-8 encoding
    logger.add(
        log_file,
        level="WARNING",
        rotation="1 day",
        retention="1 week",
        format="{time:YYYY-MM-DD HH:mm:ss} | {level} | {module}:{function}:{line} | {message}",
        encoding="utf-8"
    )
    
    return log_file

# Initialize logging when this module is imported
log_file = setup_logging()
logger.info(f"Error logs will be saved to: {log_file}")


if __name__ == "__main__":
    log_file = setup_logging()
    # Test Chinese character logging
    logger.info("测试中文日志输出") 