"""
[GENERATED BY CURSOR]
Generic HTML parser using markdownify for basic HTML to Markdown conversion.
"""

from utils.logging_config import logger
from markdownify import markdownify
from typing import Optional


def _html_to_markdown(html_content: str) -> str:
    """
    Converts HTML content to Markdown using markdownify.
    """
    try:
        return markdownify(html_content)
    except Exception as e:
        logger.error(f"Error in HTML to Markdown conversion: {e}", exc_info=True)
        return None

def extract_catalogue(html_content: str) -> Optional[str]:
    """
    Parses HTML content directly to Markdown using markdownify and extracts the title.
    
    Args:
        html_content: The HTML content to parse.
        
    Returns:
        tuple: (markdown_content, title) or (None, None) if an error occurs or content is empty.
    """
    return _html_to_markdown(html_content)

def extract_content(html_content: str) -> Optional[str]:
    """
    Parses HTML content directly to Markdown using markdownify and extracts the title.
    """
    return {
        'title': 'Untitled',
        'content': _html_to_markdown(html_content)
    }
